### ISSUE TITLE
[FEATURE] Clone Event Rules

### ISSUE THREAD

**Issue by SMAPPER** [reflexsoar/reflex-api#116]
**Is your feature request related to a problem? Please describe.**
Some event rules make sense to be per tentant even though the rule may be the same. However, currently, this is 100% manual. 

**Describe the solution you'd like**
It would be great to have a clone event rule button or something similar.

**Comment by n3tsurge** [comment]
Functionality in place and ready for testing

**Comment by SMAPPER** [comment]
This feature has been implemented and tested.
