### ISSUE TITLE
[BUG] Event Rules in Quick Filter

### ISSUE THREAD

**Issue by SMAPPER** [reflexsoar/reflex-api#159]
**Describe the bug**
If you have many event rules, the quick filter URL request is too big. As a result, all event rule names show Unknown in the quick filter bar.

**To Reproduce**
Have over 200 rules and then access the event queue.

**Comment by n3tsurge** [comment]
Issue resolved by loading the `name` and `uuid` for all available rules when the Event Queue filter bar loads, change in reflexsoar/reflex-ui@ec1fa81b3aecc849e0b395725a4a3d17bf6e0dac
