### ISSUE TITLE
[BUG] Observable strings are not URL encoded when passed to API calls

### ISSUE THREAD

**Issue by jtavan** [reflexsoar/reflex-api#166]
**Describe the bug**
Observables that start with/contain "/" break the toggle switches in the Cases -> Observables. Clicking them results in a 404. 

**To Reproduce**
1. Create a case with an observable "/bin/sh /Users/username/badfile.txt"
2. Navigate to the Observables tab and try to click on the "IOC" toggle for that observable.
3. Web browser redirects to a 404 response trying to get badfile.txt.

**Expected behavior**
Toggle switches should work as expected.

**Additional context**
The toggle switch results in an API call to https://reflex-server/api/v2.0/case/case-uuid/observables//bin/sh%20/Users/username/badfile.txt which has an extra / between "observables" and "bin". Solution is probably to fully URL encode strings being passed to API calls.

**Comment by n3tsurge** [comment]
Oh man that's embarrassing, will get a fix in for this ASAP we are planning on pushing a patch tonight for some other items so I'll work this in to it.

**Comment by jtavan** [comment]
I think spaces are encoded as %20, but other characters like / aren't encoded. Thanks for the quick response!

**Comment by n3tsurge** [comment]
I ended up using Base64 for that exact reason and found another bug at the same time.  After this makes it through my Dev/QA testing tomorrow I will release the 2022.05.01 patch which contains a bunch of fixes and enhancements as well as this item.

Appreciate you opening items and thanks for trying out the tool!  Let me know if there is anything you think needs retooling.

**Comment by n3tsurge** [comment]
This item is resolved in v2022.05.01 (7ee694ef522c30f56c646092ed3e64a47f818240)
