### ISSUE TITLE
[FEATURE] - Detections

### ISSUE THREAD

**Issue by n3tsurge** [reflexsoar/reflex-api#168]
# Overview
Create a detection framework for defining a number of detection rules that can generate alerts directly in the ReflexSOAR system.  A drop in replacement for ElastAlert or Signals.

# Key Components

## Detection
- [x] Create Detection
- [x] Edit Detection
  - [x] Add Exception
  - [x] Remove Exception
- [x] Delete Detection
- [ ] Convert from Sigma
   - [ ] Create backend field mapping for conversion (version controlled to match schema changes e.g. ECS changing)
- [ ] Export to Sigma

## Detection Repository
- [ ] Add Detection to Repository
- [ ] Share Repository with Token
- [ ] Share Repository Publicly
- [ ] Import Remote Repository

## Detection Repository Bundle
- [ ] Add multiple repositories to the bundle
- [ ] Share the bundle with Token
- [ ] Share the bundle Publicly 
- [ ] Import Bundle

# Agent Behavior

- [ ] Move the `poller` and `detector` roles to dedicated sub processes
- [ ] Detector process should check the API for new work assigned to the agent

# Agent Workload Balancing

- When a new detection is created or a new agent comes online the API will divide the work up across the entire fleet of agents that have the `detector` role assigned
- When an agent goes into an unhealthy state, a recalculation of workload balance will occur and agents will get new work definitions when they check in at their next heartbeat

**Comment by jtavan** [comment]
If you can build this to support Sigma-formatted rules directly, with an appropriately configurable field schema to match local environments and support for Elastalert-style statistical alerting, it would be super useful.

**Comment by n3tsurge** [comment]
That's the plan!  We are going to try to match all the alert types that ElastAlert has.  For rule criteria we are going to allow the user to write the alert in the backend native language or leverage sigma to translate to the backend and vice versa.

**Comment by jtavan** [comment]
Sigma Correlations compatibility for those temporal detections would be super useful.
