### ISSUE TITLE
[BUG] Unable to delete an User Role from UI

### ISSUE THREAD

**Issue by anrsec** [reflexsoar/reflex-api#198]
**Describe the bug**
Nothing happens when the `Delete` button is clicked for a Role in the System/Settings/Roles webpage.
I couldn't identify any errors or even logs related to this request. 

**To Reproduce**
1. Go to System/Settings/Roles
2. Click on the Trash Icon for one of the roles.

**Expected behavior**
The user should be prompted with a new window to `Proceed/Cancel` the deletion. 

**Screenshots**
![image](https://user-images.githubusercontent.com/61625853/174549269-acdbec8f-2d5d-45b3-9ba6-43d5a0b19656.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 
 - Browser: Brave
    Version 1.33.106 Chromium: 96.0.4664.110
 - Browser: Firefox
    Version: 101.0.1

**Comment by n3tsurge** [comment]
Will fix in a release this week

**Comment by n3tsurge** [comment]
Functionality exists and works in the API, UI component was never built

**Comment by anrsec** [comment]
Thanks for the clarifications, Brian! :pray:

**Comment by anrsec** [comment]
That's great, Brian! 
I hope I'm not too annoying with all these posts. 
At the end of the day, I use the Community version that doesn't imply any kind of software support. So feel free to ignore some of my posts sometimes :laughing:

**Comment by n3tsurge** [comment]
No these issues are perfect and greatly appreciated! This was designed for community use cuz we want to help the community fill tool gaps.  Sorry for all the bugs! Lol

**Comment by anrsec** [comment]
I'm glad and thank you for that! :pray:
