### ISSUE TITLE
[BUG] Organization entry created even though the creation process failed

### ISSUE THREAD

**Issue by anrsec** [reflexsoar/reflex-api#199]
**Describe the bug**
When creating an new organization, you are prompted to create an Admin user for that specific organization. But you are allowed to skip this part:

![image](https://user-images.githubusercontent.com/61625853/174558152-290a3b7c-d818-47fd-8193-9a97cd6a8326.png)

and this will result in an `Internal Server Error`. 

![image](https://user-images.githubusercontent.com/61625853/174558182-6a203cfe-6efe-4adf-a692-55e3d94dd8fe.png)

Although you still have to choose between `Dismiss` and `Create` options, an entry has already been created in System/Settings/Organizations.

![image](https://user-images.githubusercontent.com/61625853/174558268-e51b81a3-d434-42a9-be76-b43371277ea0.png)

Any other objects  linked to that specific organization from now on, will not work (e.g roles, users, inputs).

**To Reproduce**
1. Go to System/Settings
2. Click on Organizations/New Organization
3. Fill all the details in `Define the Organization` window. Click Next.
4. Do not fill any details in the `Create Admin User` window and just click Next.
5. Click Create and see the `Internal Server Error`.
6. Now Click Dismiss.
7. Refresh the System/Settings/Organizations page.
8. Observe the new entry.

**Expected behavior**
An entry in the Organizations Tab should not be created if the creation process has failed.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04
- Browser: Brave
  Version 1.33.106 Chromium: 96.0.4664.110
- Browser: Firefox
  Version: 101.0.1

**Comment by n3tsurge** [comment]
Enabled API validation on the Create Organizations endpoint requiring the default admin information

This is now in the dev build and will be validated shortly

**Comment by anrsec** [comment]
Thank you for considering this so quickly!
Is there any emailing list for announcing new versions available or will it just be posted on Twitter? :thinking:
