### ISSUE TITLE
Case Templates no longer displayed in Reflex-UI if Description is modified right after Case Template creation

### ISSUE THREAD

**Issue by anrsec** [reflexsoar/reflex-api#229]
### Discussed in https://github.com/reflexsoar/reflex-api/discussions/228

We tried to reproduce the issue and see what causes it and this is what we got: if a Case Template Description is modified right after Case Template creation then all Case Templates stop being displayed in the UI. 
Everything works as expected if other fields of the Case Template are changed first.

Steps:
- Create a Case Template
- Refresh the page
- Edit and only modify the Description 
- Refresh the page
- Check if Case Templates are still displayed
-----------------------------------------------------------
<div type='discussions-op-text'>

<sup>Originally posted by **anrsec** July 20, 2022</sup>
Hi,

We encountered a strange issue today when Case Templates suddenly stopped being displayed in the UI. Though, they seem to be loaded from Elastic according to browser network tools: 

![image](https://user-images.githubusercontent.com/61625853/179933478-b9395046-7538-410d-b165-8502b1de8b02.png)

We can also apply them when creating a case starting from an Event in the Queue.
![image](https://user-images.githubusercontent.com/61625853/179939415-5d95d4e0-1049-45e7-a6a2-55ede56f6388.png)

Tried to switch browsers and to rebuild reflex-api, reflex-ui and memcached docker containers without success. 
Also, searched through the docker logs but couldn't find anything related. :man_shrugging: 

Any suggestions on how I can troubleshoot further? 
</div>

**Comment by n3tsurge** [comment]
I am unable to replicate this as an Analyst user or Admin user

**Comment by n3tsurge** [comment]
I was able to replicate, this is an error that occurs when there are no tasks on the Template, will supply a fix

**Comment by n3tsurge** [comment]
Fixed and will release in the 2022.08.00 release
