### ISSUE TITLE
[BUG] RQL doesn't correctly parse raw_log.base64_decoded field

### ISSUE THREAD

**Issue by skipperblue** [reflexsoar/reflex-api#251]
**Describe the bug**
We have multiple rules that contain `raw_log.base64_decoded` that refuse to match. 
As an example: 
`title = "suspicious powershell base64"` 
matches every event with this title
```
title = "suspicious powershell base64"
and raw_log.base64_decoded exists
```
matches the same number of events, but:
```
title = "suspicious powershell base64"
and raw_log.base64_decoded contains "string" #or contains ["array"]
```
will match zero events. 

**To Reproduce**
Will provide specific example privately to not disclose private information. 

**Expected behavior**
raw_log.base64_decoded should parse content just any other filter. 

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: latest

**Additional context**
having multiple or filters in a (nest) with raw_log.base64_decoded will still correctly match on the other filters but not on raw_log.base64_decoded.

**Comment by n3tsurge** [comment]
Issue was in the raw_log field itself, the source data contained unicode null-bytes `\u0000` between each string character.

Proposing a new mutator called `strip_null_bytes` to help in these cases
