### ISSUE TITLE
[BUG] Swagger UI unavailable

### ISSUE THREAD

**Issue by pemontto** [reflexsoar/reflex-api#285]
**Describe the bug**
Just stood up the latest quickstart and was hoping to browse the API using the swagger UI. When visiting `/api/v2.0/` it attempts to load the JS and CSS from `/swaggerui` all of which 404.

**To Reproduce**
1. Open web tools
2. Browse to `https://<ReflexSOAR>/api/v2.0/`
4. See error/s

**Expected behavior**
The swagger UI with a self documenting API pops up 😄 

**Screenshots**
<img width="950" alt="SCR-20221019-lh0-2" src="https://user-images.githubusercontent.com/939704/196720030-1d74657a-e9be-414f-a0b7-c90093467bca.png">

**Comment by n3tsurge** [comment]
At the moment, this behavior is expected when running the API in a production environment.   Let me see if I can get the docs for you in the mean time, you're the first docs request.  Will allow this setting to be changed in the future to expose the docs when in a production environment via an environmental variable.

**Comment by n3tsurge** [comment]
This is the latest swagger.json from the current production release https://github.com/reflexsoar/reflex-api-swagger-spec/blob/main/2022.06.00.json

You should be able to import this directly in to Postman.  I will try to bang out #286 this weekend so you can just do it via the Swagger UI

**Comment by n3tsurge** [comment]
Just an update when you launch ReflexSOAR you can access the API spec by going to `/api/v2.0/swagger.json` instead of the file I shared, this will always give you the most up to date spec, you just don't get the UI.  The Swagger UI option is still coming in the other referenced issue.
