### ISSUE TITLE
Issue with Agent authenticating to OpenSearch 

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#401]
Hi Everyone!

I just installed Reflex-SOAR as per the quick install steps, and configured OpenSearch input with basic_auth and required credentials, 

![image](https://github.com/reflexsoar/reflex-api/assets/11851504/f1d5b1c6-101b-4129-9309-613ff7ebf633)

but the setup isn't working - as the agent is repeatedly getting failed to authenticate with OpenSearch (with the below warning msg).
```
reflex-ui              | 172.18.0.7 - - [24/May/2023:07:28:37 +0000] "GET /api/v2.0/agent/1f54e9c1-7755-440f-bdb8-03fc5ef4229b HTTP/1.1" 200 1379 "-" "reflexsoar-agent/2022.05.01" "-"
reflex-ui              | 172.18.0.7 - - [24/May/2023:07:28:37 +0000] "GET /api/v2.0/agent/heartbeat/1f54e9c1-7755-440f-bdb8-03fc5ef4229b HTTP/1.1" 200 39 "-" "reflexsoar-agent/2022.05.01" "-"
reflex-agent           | 2023-05-24 07:28:37,877 - Running agent
reflex-agent           | 2023-05-24 07:28:37,878 - Running input test-setup
reflex-agent           | 2023-05-24 07:28:37,878 - Fetching credentials
reflex-ui              | 172.18.0.7 - - [24/May/2023:07:28:37 +0000] "GET /api/v2.0/credential/ HTTP/1.1" 404 207 "-" "reflexsoar-agent/2022.05.01" "-"
reflex-ui              | 172.18.0.7 - - [24/May/2023:07:28:37 +0000] "GET /api/v2.0/credential/decrypt/ HTTP/1.1" 404 207 "-" "reflexsoar-agent/2022.05.01" "-"
opensearch             | [2023-05-24T07:28:37,901][WARN ][o.o.s.h.HTTPBasicAuthenticator] [7cf3981f9f32] Invalid 'Authorization' header, send 401 and 'WWW-Authenticate Basic'
opensearch             | [2023-05-24T07:28:37,902][WARN ][o.o.s.a.BackendRegistry  ] [7cf3981f9f32] No 'Authorization' header, send 401 and 'WWW-Authenticate Basic'
reflex-agent           | 2023-05-24 07:28:37,902 - POST https://192.168.5.126:9200/opensearch_dashboards_sample_data_logs/_search?scroll=2m [status:401 request:0.005s]
reflex-agent           | 2023-05-24 07:28:37,903 - Failed to run search, make sure the Elasticsearch cluster is reachable. AuthenticationException(401, 'Unauthorized')
reflex-agent           | 2023-05-24 07:28:37,904 - Agent sleeping for 30 seconds
reflex-ui              | 127.0.0.1 - - [24/May/2023:07:28:38 +0000] "GET / HTTP/1.1" 200 5997 "-" "curl/7.74.0" "-"
reflex-ui              | 192.168.5.105 - - [24/May/2023:07:28:46 +0000] "GET /api/v2.0/task?complete=true&broadcast=true HTTP/1.1" 200 14 "https://192.168.5.126/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
```

Also, I've manually tried to connect to the OpenSearch with the same credentials provided, which worked but the same isn't working via agent.

Couldn't figure out what I was doing wrong, any advice/guidance on how I can further troubleshoot this?

**Comment by n3tsurge** [comment]
Can you run 

```
GET reflex-inputs/_search
{}
```

From the development tools in Opensearch dashboards and confirm that the Input document has the `credential` field populated?

Did you deploy this from the quickstart or manually?

**Comment by greycel** [comment]
I've deployed using the quickstart install script.
Executed the above query and the ```credential``` field is empty.

![image](https://github.com/reflexsoar/reflex-api/assets/11851504/3026ed9b-4c4b-4549-b544-a343354e5f49)

**Comment by n3tsurge** [comment]
Not sure why that didn't populate when you created the input but there are several things we can try:

1. Recreate the input and see if the credential is empty again
2. Patch the input using dev tools

## Option 2 Instructions

1. Locate the credential UUID by running the following

```
GET reflex-credentials/_search
```

2. Copy the `uuid` of the credential
3. Find the input you wish to update

```
GET reflex-inputs/_search
```

4. Copy the `_id` of the input you wish to update
5. Create the following update query

```
POST reflex-inputs/_update/<input_id_here>
{
  "doc": {
    "credential": "<credential_uuid_here>"
  }
}
```

**Comment by greycel** [comment]
Thank you, now it worked...
