### ISSUE TITLE
Issue with agent - unable to resume already paired agent

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#404]
Hi Everyone!

I've deployed a new agent using the "Agent Pairing Token" command ``` python reflex-agent.py --pair --token <token> --console https://192.168.11.23 --roles poller,runner ``` which was successfully paired and started to pull the events. 

But for some reason in case if this agent process gets terminated and when I attempt to resume the pull activity for the same agent, getting the below error:
```
[gey@rocky reflex-agent]$ pipenv run python -u reflex-agent.py
Loading .env environment variables...
2023-05-25 04:44:14,195 - Pairing agent..
2023-05-25 04:44:14,219 - Failed to pair agent. Access token expired.
```

Again I had to delete the registered agent in the console and redeploy the agent again. 

I've followed the steps https://github.com/reflexsoar/reflex-agent/tree/master#readme but couldn't figure out how to resume an already paired agent without needing to redeploy each time? 

Any advice on how I can further troubleshoot this?

**Comment by n3tsurge** [comment]
Can you check your .env file to make sure the env var for pair mode is commented out when trying to restart an existing agent?

This agent version doesn't skip pairing if it already is paired, it does in our next release.

**Comment by greycel** [comment]
Pair mode was enabled in the ```.env``` file
Was able to resume the deployed agent after commenting ```REFLEX_AGENT_PAIR_MODE=true``` variable
Thank you, really appreciate your help.
