### ISSUE TITLE
Input (Lucene Filter) isn't working 

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#409]
Hi, 

I've installed `Reflex Version-2023.06.06-rc0` with OpenSearch and all the services are up and running.

Configured Input to pull only SYSMON events, used Lucene Filter as below:
> ![image](https://github.com/reflexsoar/reflex-api/assets/11851504/9a32028f-0bff-423b-83ba-79a4370f7dd9)

Started to receive records in the event queue, and noticed that they were all `MicroSoft-Windows-Security-Auditing` events, which I haven't configured yet, also at that moment there were no SYSMON events in the configured index.
> ![image](https://github.com/reflexsoar/reflex-api/assets/11851504/7d5e4491-027e-4095-b3ac-fc3f5b467f94)

Any advice on what to be checked...

**Comment by n3tsurge** [comment]
Check your lucene query is correct, this is a function we use in production on every input and we haven't experienced this issue.  Try wrapping the source name in quotes

Sent from my Verizon, Samsung Galaxy s
________________________________
From: Greycel ***@***.***>
Sent: Monday, June 19, 2023 12:13:38 PM
To: reflexsoar/reflex-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [reflexsoar/reflex-api] Input (Lucene Filter) isn't working (Issue #409)


Hi,

I've installed Reflex Version-2023.06.06-rc0 with OpenSearch and all the services are up and running.

Configured Input to pull only SYSMON events, used Lucene Filter as below:

[image]<https://user-images.githubusercontent.com/11851504/246881425-9a32028f-0bff-423b-83ba-79a4370f7dd9.png>

Started to receive records in the event queue, and noticed that they were all MicroSoft-Windows-Security-Auditing events, which I haven't configured yet, also at that moment there were no SYSMON events in the configured index.

[image]<https://user-images.githubusercontent.com/11851504/246882201-7d5e4491-027e-4095-b3ac-fc3f5b467f94.png>

Any advice on what to be checked...

**Comment by greycel** [comment]
Thank you, It worked...
