### ISSUE TITLE
Agents not getting listed in new release | Observable options not working

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#439]
Hi,
I've noticed the below issue after updating `UI, API, AGENT` to the latest release - [v2023.09.05-rc0](https://github.com/reflexsoar/reflex-api/releases/tag/v2023.09.05-rc0)

1) The grid on the agent's page keeps loading but nothing is listed. I'm able to add new agents, this increments the agent count but the list of paired agents isn't visible.
2) Observable options `Copy Value, Add to List` in the `Actions` drop-down menu of the Event Queue page aren't working. (This is the same in the previous release as well)

**Comment by n3tsurge** [comment]
I am cutting a new release candidate this morning that should fix #1.  #2 I'll try to add back before I cut the release candidate as well.

**Comment by n3tsurge** [comment]
Fixes for both should be available in `v2023.09.12-rc0` when it's done building on Docker Hub
