### ISSUE TITLE
RQL query not working with "raw_log" flat keys

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#444]
Hi @n3tsurge 
I've created new issue as the old one #436 closed.
Updated to the new release version [2023.09.14-rc0](https://github.com/reflexsoar/reflex-api/releases/tag/v2023.09.14-rc0). 
But RQL isn't working in this new release with flat keys `{"field.name.here": "value"}`, behavior is the same as earlier #436, 

Thanks.

**Comment by n3tsurge** [comment]
Wow you deploy new patches quickly.  Let me look this morning

**Comment by n3tsurge** [comment]
I think I have this nipped. Flat keys would work at the root of the event but nested further down.  Ill push a new RC here in an hour.

![image](https://github.com/reflexsoar/reflex-api/assets/1574741/0303f53d-7d6b-4f88-83c1-bbbe9ddebeac)
