### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by n3tsurge** [reflexsoar/reflex-api#57]
- [ ] Create a Super Admin that can create new organizations, shops that don't need multi-tenancy will just use the default org
- [ ] Create page in UI to add/remove organizations
- [ ] Create manage.py script to create organizations from the CLI (for bootstrapping new orgs)
- [ ] Create relationships between all objects to an organization to prevent cross organization boundaries

**Comment by SMAPPER** [comment]
Implemented
